import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";

export class FoodError extends Error { constructor(readonly code: string, readonly details?: Record<string, unknown>) { super(code); } }
type Scope = "all" | "local" | "custom";
type ServingInput = { label: string; amount: number; unit: "g" | "ml"; equivalentG?: number; equivalentMl?: number; isDefault?: boolean };
type Nutrients = { energyKcal: number; proteinG: number; fatG?: number; carbG?: number };
type CustomInput = { name: string; englishName?: string; brand?: string; nutrients: Nutrients; aliases?: string[]; servings?: ServingInput[] };
type SearchInput = { q: string; limit: number; scope: Scope; cursor?: string };
type UpdateInput = { name?: string; version?: number; nutrients?: Partial<Nutrients> };
type Options = { now?: () => number; id?: () => string };
type Cursor = { r: number; f: number; t: number; n: string; i: string };
const normalize = (value: string) => value.trim().replace(/\s+/g, " ").toLocaleLowerCase();
const positive = (value: unknown) => typeof value === "number" && Number.isFinite(value) && value > 0;
const nutrientRows = (value: Nutrients | Partial<Nutrients>) => [["energy_kcal", "能量", "kcal", value.energyKcal], ["protein_g", "蛋白质", "g", value.proteinG], ["fat_g", "脂肪", "g", value.fatG], ["carbohydrate_g", "碳水化合物", "g", value.carbG]] as const;
function encodeCursor(cursor: Cursor) { return Buffer.from(JSON.stringify(cursor)).toString("base64url"); }
function decodeCursor(value: string): Cursor { try { if (!/^[A-Za-z0-9_-]+$/.test(value)) throw new Error(); const parsed: unknown = JSON.parse(Buffer.from(value, "base64url").toString("utf8")); if (parsed === null || typeof parsed !== "object") throw new Error(); const c = parsed as Partial<Cursor>; if (!Number.isInteger(c.r) || !Number.isInteger(c.f) || !Number.isFinite(c.t) || typeof c.n !== "string" || typeof c.i !== "string" || encodeCursor(c as Cursor) !== value) throw new Error(); return c as Cursor; } catch { throw new FoodError("FOOD_INVALID_CURSOR"); } }
function assertServing(input: ServingInput) { if (!input || typeof input.label !== "string" || !input.label.trim() || !positive(input.amount) || (input.unit !== "g" && input.unit !== "ml") || (!positive(input.equivalentG) && !positive(input.equivalentMl))) throw new FoodError("FOOD_INVALID_SERVING"); }
function assertCustom(input: CustomInput) { if (!input || typeof input.name !== "string" || !input.nutrients || !positive(input.nutrients.energyKcal) || !positive(input.nutrients.proteinG) || (input.aliases && (!Array.isArray(input.aliases) || input.aliases.some((x) => typeof x !== "string" || !x.trim()))) || (input.servings && !Array.isArray(input.servings))) throw new FoodError("FOOD_INVALID_CUSTOM"); for (const serving of input.servings ?? []) assertServing(serving); }

export function createFoodCatalog(sqlite: DatabaseSync, options: Options = {}) {
  const now = options.now ?? Date.now; const id = options.id ?? randomUUID;
  const active = (foodId: string) => { if (!sqlite.prepare("SELECT 1 FROM food_item WHERE id=? AND active=1").get(foodId)) throw new FoodError("FOOD_NOT_FOUND"); };
  const editable = (foodId: string) => { if (!sqlite.prepare("SELECT 1 FROM food_source_record WHERE food_id=? AND source_type IN ('custom','user_label') LIMIT 1").get(foodId)) throw new FoodError("FOOD_REFERENCE_READ_ONLY"); };
  const addAliasRow = (foodId: string, alias: string) => { const text = alias.trim().replace(/\s+/g, " "); const normalized = normalize(text); if (!text) throw new FoodError("FOOD_INVALID_ALIAS"); if (sqlite.prepare("SELECT 1 FROM food_alias WHERE food_id=? AND alias_normalized=?").get(foodId, normalized)) throw new FoodError("FOOD_ALIAS_DUPLICATE"); const aliasId=id(); sqlite.prepare("INSERT INTO food_alias (id,food_id,alias,alias_normalized,alias_type,user_defined) VALUES (?,?,?,?,'synonym',1)").run(aliasId,foodId,text,normalized); return aliasId; };
  const addServingRow = (foodId: string, input: ServingInput) => { assertServing(input); const servingId=id(); sqlite.prepare("INSERT INTO food_serving (id,food_id,label,amount,unit,equivalent_g,equivalent_ml,sort_order,source,is_default) VALUES (?,?,?,?,?,?,?,0,'user',?)").run(servingId,foodId,input.label.trim(),input.amount,input.unit,input.equivalentG ?? null,input.equivalentMl ?? null,input.isDefault?1:0); return servingId; };
  const primarySource = (foodId: string) => sqlite.prepare("SELECT id FROM food_source_record WHERE food_id=? AND is_primary=1").get(foodId) as { id: string } | undefined;
  const writeNutrients = (foodId: string, sourceId: string, values: Nutrients | Partial<Nutrients>, timestamp: number) => { for (const [key,label,unit,amount] of nutrientRows(values)) if (amount !== undefined) { sqlite.prepare("INSERT OR IGNORE INTO food_nutrient_definition (id,display_name,unit,nutrient_group,display_order,summable) VALUES (?,?,?,'macro',0,1)").run(key,label,unit); sqlite.prepare("INSERT INTO food_nutrient_value (id,food_id,source_record_id,nutrient_id,amount_numeric,amount_raw,value_status,basis_amount,basis_unit,created_at) VALUES (?,?,?,?,?,?, 'known',100,'g',?)").run(id(),foodId,sourceId,key,amount,String(amount),timestamp); } };
  const summary = (foodId: string) => { const source=primarySource(foodId); const rows=(source ? sqlite.prepare("SELECT nutrient_id,amount_numeric FROM food_nutrient_value WHERE food_id=? AND source_record_id=?").all(foodId,source.id) : []) as Array<{nutrient_id:string;amount_numeric:number|null}>; const value=(key:string) => rows.find((x)=>x.nutrient_id===key)?.amount_numeric ?? null; return {energyKcal:value("energy_kcal"),proteinG:value("protein_g"),fatG:value("fat_g"),carbG:value("carbohydrate_g")}; };
  return {
    search(input: SearchInput) {
      if (!Number.isInteger(input.limit) || input.limit < 1 || input.limit > 50) throw new FoodError("FOOD_INVALID_LIMIT"); if (!(["all","local","custom"] as string[]).includes(input.scope)) throw new FoodError("FOOD_INVALID_SCOPE"); const q=normalize(input.q); if (!q) return {data:[],nextCursor:null}; const cursor=input.cursor ? decodeCursor(input.cursor) : null; const scope=input.scope==="custom" ? "AND fi.food_type='custom'" : input.scope==="local" ? "AND fi.food_type<>'custom'" : ""; const ftsQuery=`${q.replace(/["*]/g, "")}*`;
      const rows=sqlite.prepare(`WITH candidates(food_id,rank) AS (SELECT id,3 FROM food_item WHERE lower(primary_name)=? UNION ALL SELECT food_id,3 FROM food_alias WHERE alias_normalized=? UNION ALL SELECT id,2 FROM food_item WHERE lower(primary_name) LIKE ? UNION ALL SELECT food_id,2 FROM food_alias WHERE alias_normalized LIKE ? UNION ALL SELECT food_id,1 FROM food_search_fts WHERE food_search_fts MATCH ?), ranked AS (SELECT fi.id,fi.primary_name name,fi.english_name englishName,fi.brand,fi.default_basis basis,fi.source_quality quality,sr.source_type source,MAX(c.rank) rank,COALESCE(st.favorite,0) favorite,COALESCE(st.last_used_at,0) recentAt,lower(fi.primary_name) normalizedName FROM candidates c JOIN food_item fi ON fi.id=c.food_id LEFT JOIN food_source_record sr ON sr.food_id=fi.id AND sr.is_primary=1 LEFT JOIN food_search_stats st ON st.food_id=fi.id WHERE fi.active=1 ${scope} GROUP BY fi.id) SELECT * FROM ranked WHERE (? IS NULL OR rank < ? OR (rank=? AND (favorite < ? OR (favorite=? AND (recentAt < ? OR (recentAt=? AND (normalizedName > ? OR (normalizedName=? AND id > ?)))))))) ORDER BY rank DESC,favorite DESC,recentAt DESC,normalizedName,id LIMIT ?`).all(q,q,`${q}%`,`${q}%`,ftsQuery,cursor?.r ?? null,cursor?.r ?? 0,cursor?.r ?? 0,cursor?.f ?? 0,cursor?.f ?? 0,cursor?.t ?? 0,cursor?.t ?? 0,cursor?.n ?? "",cursor?.n ?? "",cursor?.i ?? "",input.limit+1) as Array<Record<string,unknown>>;
      const page=rows.slice(0,input.limit).map((row)=>({id:String(row.id),name:String(row.name),englishName:row.englishName as string|null,brand:row.brand as string|null,source:row.source ?? null,quality:row.quality,basis:{amount:100,unit:row.basis==="liquid_100ml"?"ml":"g"},summary:summary(String(row.id)),favorite:row.favorite===1,recent:Number(row.recentAt)>0})); const last=rows[input.limit-1]; return {data:page,nextCursor:rows.length>input.limit && last ? encodeCursor({r:Number(last.rank),f:Number(last.favorite),t:Number(last.recentAt),n:String(last.normalizedName),i:String(last.id)}) : null};
    }, summary,
    detail(foodId: string) { const food=sqlite.prepare("SELECT fi.*,sr.source_type source,sr.source_url sourceUrl,fd.version datasetVersion,COALESCE(st.favorite,0) favorite,COALESCE(st.use_count,0) useCount,st.last_used_at lastUsedAt FROM food_item fi LEFT JOIN food_source_record sr ON sr.food_id=fi.id AND sr.is_primary=1 LEFT JOIN food_dataset fd ON fd.id=sr.dataset_id LEFT JOIN food_search_stats st ON st.food_id=fi.id WHERE fi.id=? AND fi.active=1").get(foodId) as Record<string,unknown>|undefined; if (!food) return null; const source=primarySource(foodId); return {id:food.id,name:food.primary_name,englishName:food.english_name,brand:food.brand,source:food.source,sourceUrl:food.sourceUrl,quality:food.source_quality,datasetVersion:food.datasetVersion,favorite:food.favorite===1,usage:{count:food.useCount,lastUsedAt:food.lastUsedAt},aliases:sqlite.prepare("SELECT id,alias,alias_type type,user_defined userDefined FROM food_alias WHERE food_id=? ORDER BY alias_normalized").all(foodId),servings:sqlite.prepare("SELECT id,label,amount,unit,equivalent_g equivalentG,equivalent_ml equivalentMl,source,is_default isDefault FROM food_serving WHERE food_id=? ORDER BY sort_order,id").all(foodId),nutrients:source ? sqlite.prepare("SELECT nv.nutrient_id id,nd.display_name name,nd.unit,nv.amount_numeric amount,nv.amount_raw raw,nv.value_status status,nv.basis_amount basisAmount,nv.basis_unit basisUnit FROM food_nutrient_value nv JOIN food_nutrient_definition nd ON nd.id=nv.nutrient_id WHERE nv.food_id=? AND nv.source_record_id=? ORDER BY nd.display_order,nv.nutrient_id").all(foodId,source.id) : []}; },
    createCustom(input: CustomInput) { assertCustom(input); const foodId=id(),sourceId=id(),timestamp=now(); sqlite.exec("BEGIN IMMEDIATE"); try { sqlite.prepare("INSERT INTO food_item (id,canonical_key,primary_name,english_name,brand,food_type,default_basis,source_quality,active,created_at,updated_at) VALUES (?,?,?,?,?,'custom','edible_100g','C',1,?,?)").run(foodId,`custom:${foodId}`,input.name.trim(),input.englishName ?? null,input.brand ?? null,timestamp,timestamp); sqlite.prepare("INSERT INTO food_source_record (id,food_id,source_type,raw_json,imported_at,is_primary) VALUES (?,?,'custom',?,?,1)").run(sourceId,foodId,JSON.stringify(input),timestamp); writeNutrients(foodId,sourceId,input.nutrients,timestamp); for(const alias of input.aliases ?? []) addAliasRow(foodId,alias); for(const serving of input.servings ?? []) addServingRow(foodId,serving); sqlite.exec("COMMIT"); return {id:foodId}; } catch(error) { sqlite.exec("ROLLBACK"); throw error; } },
    update(foodId:string,input:UpdateInput) { active(foodId); editable(foodId); if(input.name===undefined&&input.nutrients===undefined) throw new FoodError("FOOD_EMPTY_UPDATE"); if(input.name!==undefined&&!input.name.trim()) throw new FoodError("FOOD_INVALID_CUSTOM"); if(input.nutrients&&Object.values(input.nutrients).some((x)=>x!==undefined&&!positive(x))) throw new FoodError("FOOD_INVALID_CUSTOM"); const timestamp=now(); const current=sqlite.prepare("SELECT updated_at FROM food_item WHERE id=?").get(foodId) as {updated_at:number}; if(input.version!==undefined&&current.updated_at!==input.version) throw new FoodError("FOOD_VERSION_CONFLICT"); sqlite.exec("BEGIN IMMEDIATE"); try { sqlite.prepare("UPDATE food_item SET primary_name=COALESCE(?,primary_name),updated_at=? WHERE id=?").run(input.name?.trim() ?? null,timestamp,foodId); if(input.nutrients){const old=primarySource(foodId);if(!old)throw new FoodError("FOOD_NOT_FOUND");const previous=sqlite.prepare("SELECT nutrient_id,amount_numeric,amount_raw,value_status,basis_amount,basis_unit,confidence FROM food_nutrient_value WHERE food_id=? AND source_record_id=?").all(foodId,old.id) as Array<{nutrient_id:string;amount_numeric:number|null;amount_raw:string|null;value_status:string;basis_amount:number;basis_unit:string;confidence:number|null}>;const sourceId=id();sqlite.prepare("UPDATE food_source_record SET is_primary=0 WHERE id=?").run(old.id);sqlite.prepare("INSERT INTO food_source_record (id,food_id,source_type,raw_json,imported_at,is_primary) VALUES (?,?,'custom',?,?,1)").run(sourceId,foodId,JSON.stringify(input),timestamp);for(const row of previous)sqlite.prepare("INSERT INTO food_nutrient_value (id,food_id,source_record_id,nutrient_id,amount_numeric,amount_raw,value_status,basis_amount,basis_unit,confidence,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").run(id(),foodId,sourceId,row.nutrient_id,row.amount_numeric,row.amount_raw,row.value_status,row.basis_amount,row.basis_unit,row.confidence,timestamp);for(const [key,,,amount] of nutrientRows(input.nutrients))if(amount!==undefined)sqlite.prepare("UPDATE food_nutrient_value SET amount_numeric=?,amount_raw=?,value_status='known' WHERE food_id=? AND source_record_id=? AND nutrient_id=?").run(amount,String(amount),foodId,sourceId,key);}sqlite.exec("COMMIT");}catch(error){sqlite.exec("ROLLBACK");throw error;}return this.detail(foodId); },
    addAlias(foodId:string,alias:string) { active(foodId); return addAliasRow(foodId,alias); }, deleteAlias(foodId:string,aliasId:string) { active(foodId); const row=sqlite.prepare("SELECT user_defined FROM food_alias WHERE id=? AND food_id=?").get(aliasId,foodId) as {user_defined?:number}|undefined;if(!row||row.user_defined!==1)throw new FoodError("FOOD_ALIAS_READ_ONLY");sqlite.prepare("DELETE FROM food_alias WHERE id=?").run(aliasId); },
    addServing(foodId:string,input:ServingInput) { active(foodId); return addServingRow(foodId,input); }, updateServing(foodId:string,servingId:string,input:ServingInput) { active(foodId);assertServing(input);const row=sqlite.prepare("SELECT source FROM food_serving WHERE id=? AND food_id=?").get(servingId,foodId) as {source?:string}|undefined;if(!row||row.source!=="user")throw new FoodError("FOOD_SERVING_READ_ONLY");sqlite.prepare("UPDATE food_serving SET label=?,amount=?,unit=?,equivalent_g=?,equivalent_ml=?,is_default=? WHERE id=?").run(input.label.trim(),input.amount,input.unit,input.equivalentG ?? null,input.equivalentMl ?? null,input.isDefault?1:0,servingId); }, deleteServing(foodId:string,servingId:string) { active(foodId);const row=sqlite.prepare("SELECT source FROM food_serving WHERE id=? AND food_id=?").get(servingId,foodId) as {source?:string}|undefined;if(!row||row.source!=="user")throw new FoodError("FOOD_SERVING_READ_ONLY");sqlite.prepare("DELETE FROM food_serving WHERE id=?").run(servingId); },
    setFavorite(foodId:string,favorite:boolean) { active(foodId);sqlite.prepare("INSERT INTO food_search_stats (food_id,favorite) VALUES (?,?) ON CONFLICT(food_id) DO UPDATE SET favorite=excluded.favorite").run(foodId,favorite?1:0); },
  };
}
